export type Car = {
  id: string;
  slug: string;
  make: string;
  model: string;
  year: number;
  mileage: number;
  fuel: string;
  transmission: string;
  drivetrain: string;
  body: string;
  bodyType: string;
  color: string;
  price: number;
  images: string[];
  featured: boolean;
  title: string;
  description: string;
  features: string[];
};

export const cars: Car[] = [
  {
    id: "1",
    slug: "volvo-v90-d4-awd",
    make: "Volvo",
    model: "V90 D4 AWD",
    title: "Volvo V90 D4 AWD",
    year: 2017,
    mileage: 12300,
    fuel: "Diesel",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "Kombi",
    bodyType: "Kombi",
    color: "Svart",
    price: 249900,
    images: ["https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&h=600&fit=crop"],
    featured: true,
    description: "Elegant och rymlig familjebil med kraftfull dieselmotor och fyrhjulsdrift. Perfekt för svenska vägar.",
    features: ["Läderklädsel", "Panoramatak", "Adaptiv farthållare", "Parkeringskamera", "LED-strålkastare", "Navigation"],
  },
  {
    id: "2",
    slug: "bmw-x5-xdrive30d",
    make: "BMW",
    model: "X5 xDrive30d",
    title: "BMW X5 xDrive30d",
    year: 2019,
    mileage: 8500,
    fuel: "Diesel",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "SUV",
    bodyType: "SUV",
    color: "Vit",
    price: 449900,
    images: ["https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop"],
    featured: true,
    description: "Premium SUV med exceptionell körglädje och avancerad teknik. Lyx och prestanda i perfekt balans.",
    features: ["Luftfjädring", "Head-up display", "Massage i säten", "Harman Kardon", "Elbaklucka", "Panoramatak"],
  },
  {
    id: "3",
    slug: "vw-golf-14-tsi",
    make: "Volkswagen",
    model: "Golf 1.4 TSI",
    title: "Volkswagen Golf 1.4 TSI",
    year: 2020,
    mileage: 4200,
    fuel: "Bensin",
    transmission: "Manuell",
    drivetrain: "FWD",
    body: "Halvkombi",
    bodyType: "Halvkombi",
    color: "Grå",
    price: 189900,
    images: ["https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800&h=600&fit=crop"],
    featured: false,
    description: "Pålitlig och bränslesnål stadsbil med modern utrustning. Perfekt för både stad och landsvägskörning.",
    features: ["Klimatanläggning", "Cruise control", "Apple CarPlay", "Parkeringssensorer", "Multifunktionsratt"],
  },
  {
    id: "4",
    slug: "audi-a4-avant-20-tdi",
    make: "Audi",
    model: "A4 Avant 2.0 TDI",
    title: "Audi A4 Avant 2.0 TDI",
    year: 2018,
    mileage: 9800,
    fuel: "Diesel",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "Kombi",
    bodyType: "Kombi",
    color: "Blå",
    price: 279900,
    images: ["https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop"],
    featured: false,
    description: "Stilren sportkombi med quattro fyrhjulsdrift. Elegant design möter praktisk funktionalitet.",
    features: ["MMI Navigation", "LED-strålkastare", "Elstol", "Parkeringskamera", "Adaptiv farthållare"],
  },
  {
    id: "5",
    slug: "tesla-model-3-long-range",
    make: "Tesla",
    model: "Model 3 Long Range",
    title: "Tesla Model 3 Long Range",
    year: 2021,
    mileage: 2100,
    fuel: "El",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "Sedan",
    bodyType: "Sedan",
    color: "Röd",
    price: 399900,
    images: ["https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&h=600&fit=crop"],
    featured: true,
    description: "Framtidens bil är här! Lång räckvidd, imponerande prestanda och självstyrande funktioner.",
    features: ["Autopilot", "15-tums pekskärm", "Premium ljudsystem", "Glastak", "Sportläge", "OTA-uppdateringar"],
  },
  {
    id: "6",
    slug: "mercedes-c-class-220d",
    make: "Mercedes-Benz",
    model: "C 220d",
    title: "Mercedes-Benz C 220d",
    year: 2019,
    mileage: 7200,
    fuel: "Diesel",
    transmission: "Automat",
    drivetrain: "RWD",
    body: "Sedan",
    bodyType: "Sedan",
    color: "Silver",
    price: 329900,
    images: ["https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&h=600&fit=crop"],
    featured: false,
    description: "Lyxsedan med klassisk elegans och moderna tekniklösningar. Komfort och prestanda i världsklass.",
    features: ["Burmester ljudsystem", "Ambient belysning", "MBUX", "Luftfjädring", "Keyless-Go", "Backkamera"],
  },
  {
    id: "7",
    slug: "volvo-xc60-t8",
    make: "Volvo",
    model: "XC60 T8 Twin Engine",
    title: "Volvo XC60 T8 Twin Engine",
    year: 2020,
    mileage: 5800,
    fuel: "Hybrid",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "SUV",
    bodyType: "SUV",
    color: "Vit",
    price: 459900,
    images: ["https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&h=600&fit=crop"],
    featured: true,
    description: "Kraftfull laddhybrid SUV med svensk design. Kombinerar prestanda med miljömedvetenhet.",
    features: ["Bowers & Wilkins", "360-kamera", "Pilot Assist", "Luftkonditionering", "Panoramatak", "Dragkrok"],
  },
  {
    id: "8",
    slug: "audi-q5-40-tdi",
    make: "Audi",
    model: "Q5 40 TDI",
    title: "Audi Q5 40 TDI",
    year: 2018,
    mileage: 11200,
    fuel: "Diesel",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "SUV",
    bodyType: "SUV",
    color: "Grå",
    price: 349900,
    images: ["https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&q=80"],
    featured: false,
    description: "Allsidig premium-SUV med quattro och Virtual Cockpit. Bekväm på långa resor.",
    features: ["Virtual Cockpit", "Bang & Olufsen", "Alcantara", "Elbaklucka", "Matrix LED", "Adaptive Cruise"],
  },
  {
    id: "9",
    slug: "bmw-3-series-320d",
    make: "BMW",
    model: "320d xDrive",
    title: "BMW 320d xDrive",
    year: 2017,
    mileage: 14500,
    fuel: "Diesel",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "Sedan",
    bodyType: "Sedan",
    color: "Svart",
    price: 239900,
    images: ["https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&h=600&fit=crop"],
    featured: false,
    description: "Sportsedan med perfekt balans mellan komfort och körglädje. BMW när det är som bäst.",
    features: ["M Sport paket", "Professional Navigation", "LED-strålkastare", "Adaptiv farthållare", "Sportläge"],
  },
  {
    id: "10",
    slug: "vw-passat-variant",
    make: "Volkswagen",
    model: "Passat Variant 2.0 TDI",
    title: "Volkswagen Passat Variant 2.0 TDI",
    year: 2019,
    mileage: 6700,
    fuel: "Diesel",
    transmission: "Automat",
    drivetrain: "FWD",
    body: "Kombi",
    bodyType: "Kombi",
    color: "Blå",
    price: 269900,
    images: ["https://images.unsplash.com/photo-1552519507-0b63f22e8ee4?w=800&h=600&fit=crop"],
    featured: false,
    description: "Rymlig och praktisk familjebil med moderna säkerhetssystem. Bekväm på alla resor.",
    features: ["Discover Pro", "Area View", "ACC", "LED Plus", "Elbaklucka", "Drag"],
  },
  {
    id: "11",
    slug: "toyota-rav4-hybrid",
    make: "Toyota",
    model: "RAV4 Hybrid AWD",
    title: "Toyota RAV4 Hybrid AWD",
    year: 2021,
    mileage: 3200,
    fuel: "Hybrid",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "SUV",
    bodyType: "SUV",
    color: "Silver",
    price: 369900,
    images: ["https://images.unsplash.com/photo-1581540222194-0def2dda95b8?w=800&h=600&fit=crop"],
    featured: true,
    description: "Pålitlig hybrid-SUV med låg bränsleförbrukning. Toyotas legendära kvalitet.",
    features: ["JBL Premium Sound", "Bi-LED", "Head-up display", "Adaptiv farthållare", "Backkamera", "Elstol"],
  },
  {
    id: "12",
    slug: "kia-sportage-phev",
    make: "Kia",
    model: "Sportage PHEV",
    title: "Kia Sportage PHEV",
    year: 2022,
    mileage: 1500,
    fuel: "Hybrid",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "SUV",
    bodyType: "SUV",
    color: "Vit",
    price: 429900,
    images: ["https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=800&h=600&fit=crop"],
    featured: false,
    description: "Modern laddhybrid med imponerande räckvidd på el. Stilren design och rik utrustning.",
    features: ["12,3 tum skärm", "BOSE", "Panoramatak", "Adaptiv fjädring", "HUD", "Trådlös laddning"],
  },
  {
    id: "13",
    slug: "mercedes-e-class-300de",
    make: "Mercedes-Benz",
    model: "E 300de Plug-in Hybrid",
    title: "Mercedes-Benz E 300de",
    year: 2021,
    mileage: 4200,
    fuel: "Hybrid",
    transmission: "Automat",
    drivetrain: "RWD",
    body: "Sedan",
    bodyType: "Sedan",
    color: "Mörkblå",
    price: 489900,
    images: ["https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&h=600&fit=crop"],
    featured: true,
    description: "Elegant laddhybrid med exceptionell komfort och avancerad teknologi. Perfekt kombination av lyx och effektivitet.",
    features: ["Multibeam LED", "Widescreen Cockpit", "Burmester 3D", "Luftfjädring", "Driving Assistance Plus", "Exclusive interiör"],
  },
  {
    id: "14",
    slug: "porsche-cayenne-e-hybrid",
    make: "Porsche",
    model: "Cayenne E-Hybrid",
    title: "Porsche Cayenne E-Hybrid",
    year: 2021,
    mileage: 3800,
    fuel: "Hybrid",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "SUV",
    bodyType: "SUV",
    color: "Svart",
    price: 749900,
    images: ["https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800&h=600&fit=crop"],
    featured: true,
    description: "Prestanda-SUV med hybridteknik. Kraftfull acceleration kombinerad med låg bränsleförbrukning.",
    features: ["Sport Chrono", "PASM luftfjädring", "Panoramatak", "BOSE Surround", "Matrix LED", "21-tums sportfälgar"],
  },
  {
    id: "15",
    slug: "volvo-s90-t8-inscription",
    make: "Volvo",
    model: "S90 T8 Inscription",
    title: "Volvo S90 T8 Inscription",
    year: 2020,
    mileage: 6200,
    fuel: "Hybrid",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "Sedan",
    bodyType: "Sedan",
    color: "Grå",
    price: 469900,
    images: ["https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&q=85"],
    featured: false,
    description: "Skandinavisk lyx i toppklass. Laddhybrid med exklusiv Inscription-utrustning och förstklassig komfort.",
    features: ["Nappa läder", "Bowers & Wilkins", "Massage", "4-zons klimat", "IntelliSafe Pro", "19-tums diamantsågade fälgar"],
  },
  {
    id: "16",
    slug: "bmw-i4-edrive40",
    make: "BMW",
    model: "i4 eDrive40",
    title: "BMW i4 eDrive40",
    year: 2022,
    mileage: 2800,
    fuel: "El",
    transmission: "Automat",
    drivetrain: "RWD",
    body: "Sedan",
    bodyType: "Sedan",
    color: "Vit",
    price: 569900,
    images: ["https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&h=600&fit=crop&q=85"],
    featured: true,
    description: "Elektrisk Gran Coupé med imponerande räckvidd på 590 km. Sportig körkaraktär med noll utsläpp.",
    features: ["Curved Display", "Live Cockpit Pro", "Harman Kardon", "Driving Assistant Pro", "Parking Assistant Plus", "Comfort Access"],
  },
  {
    id: "17",
    slug: "audi-e-tron-55-quattro",
    make: "Audi",
    model: "e-tron 55 quattro",
    title: "Audi e-tron 55 quattro",
    year: 2021,
    mileage: 5100,
    fuel: "El",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "SUV",
    bodyType: "SUV",
    color: "Grå",
    price: 629900,
    images: ["https://images.unsplash.com/photo-1614200187524-dc4b892acf16?w=800&h=600&fit=crop&q=85"],
    featured: false,
    description: "Premiär elektrisk SUV med quattro fyrhjulsdrift. 95 kWh batteri ger upp till 436 km räckvidd.",
    features: ["Virtual Cockpit Plus", "Bang & Olufsen 3D", "Matrix LED", "22-tums fälgar", "Luftfjädring", "360-kamera"],
  },
  {
    id: "18",
    slug: "lexus-rx-450h",
    make: "Lexus",
    model: "RX 450h AWD",
    title: "Lexus RX 450h AWD",
    year: 2020,
    mileage: 4900,
    fuel: "Hybrid",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "SUV",
    bodyType: "SUV",
    color: "Svart",
    price: 419900,
    images: ["https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&h=600&fit=crop&q=85"],
    featured: false,
    description: "Japansk lyx-SUV med legendarisk tillförlitlighet. Hybrid-teknik för effektiv körning.",
    features: ["Mark Levinson", "Panoramatak", "Head-up display", "Adaptiv farthållare", "Premium Nappa läder", "Pre-collision system"],
  },
  {
    id: "19",
    slug: "polestar-2-long-range",
    make: "Polestar",
    model: "2 Long Range AWD",
    title: "Polestar 2 Long Range AWD",
    year: 2022,
    mileage: 1800,
    fuel: "El",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "Sedan",
    bodyType: "Halvkombi",
    color: "Grå",
    price: 489900,
    images: ["https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&h=600&fit=crop&q=80"],
    featured: true,
    description: "Svensk elprestanda med 78 kWh batteri. Upp till 540 km räckvidd och 408 hk. Android Automotive inbyggt.",
    features: ["Pilot pack", "Plus pack", "Panoramatak", "Harman Kardon", "Vegan interiör", "OTA-uppdateringar"],
  },
  {
    id: "20",
    slug: "jaguar-i-pace-hse",
    make: "Jaguar",
    model: "I-PACE HSE",
    title: "Jaguar I-PACE HSE",
    year: 2021,
    mileage: 3600,
    fuel: "El",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "SUV",
    bodyType: "SUV",
    color: "Blå",
    price: 579900,
    images: ["https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&h=600&fit=crop&q=90"],
    featured: false,
    description: "Prisbelönad elektrisk SUV med brittisk elegans. 90 kWh batteri och 470 km räckvidd.",
    features: ["Meridian 3D", "Adaptive Dynamics", "Interactive Driver Display", "360-kamera", "Panoramatak", "Keyless entry"],
  },
  {
    id: "21",
    slug: "ford-mustang-mach-e",
    make: "Ford",
    model: "Mustang Mach-E AWD",
    title: "Ford Mustang Mach-E AWD",
    year: 2022,
    mileage: 2300,
    fuel: "El",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "SUV",
    bodyType: "SUV",
    color: "Röd",
    price: 499900,
    images: ["https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800&h=600&fit=crop"],
    featured: false,
    description: "Elektrisk Mustang-SUV med ikonisk design. Längre räckvidd med 98 kWh Extended Range batteri - upp till 600 km.",
    features: ["15,5-tums SYNC", "B&O Premium", "Panoramatak", "Ford Co-Pilot360", "Hands-Free Active Drive", "FordPass"],
  },
  {
    id: "22",
    slug: "mazda-mx-30-ev",
    make: "Mazda",
    model: "MX-30 EV",
    title: "Mazda MX-30 EV",
    year: 2021,
    mileage: 4100,
    fuel: "El",
    transmission: "Automat",
    drivetrain: "FWD",
    body: "SUV",
    bodyType: "SUV",
    color: "Grå",
    price: 319900,
    images: ["https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=800&h=600&fit=crop&q=85"],
    featured: false,
    description: "Kompakt elektrisk crossover med unika freestyle-dörrar. Miljövänliga material och innovativ design.",
    features: ["7-tums infotainment", "BOSE", "Freestyle dörrar", "Kork interiör", "i-Activsense", "Head-up display"],
  },
  {
    id: "23",
    slug: "hyundai-ioniq-5",
    make: "Hyundai",
    model: "IONIQ 5 AWD",
    title: "Hyundai IONIQ 5 AWD",
    year: 2022,
    mileage: 1900,
    fuel: "El",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "SUV",
    bodyType: "SUV",
    color: "Vit",
    price: 469900,
    images: ["https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&h=600&fit=crop&q=90"],
    featured: true,
    description: "Framtidens design möter 800V-teknik. Snabbladdning 10-80% på 18 minuter. Räckvidd upp till 481 km.",
    features: ["Dual 12,3 tum display", "BOSE Premium", "V2L funktion", "Augmented Reality HUD", "Relaxation stolar", "20-tums fälgar"],
  },
  {
    id: "24",
    slug: "mini-cooper-se",
    make: "MINI",
    model: "Cooper SE Electric",
    title: "MINI Cooper SE Electric",
    year: 2021,
    mileage: 3500,
    fuel: "El",
    transmission: "Automat",
    drivetrain: "FWD",
    body: "Halvkombi",
    bodyType: "Halvkombi",
    color: "Grön",
    price: 279900,
    images: ["https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800&h=600&fit=crop&q=85"],
    featured: false,
    description: "Elektrisk MINI med klassisk go-kart känsla. Perfekt stadsbil med 234 km räckvidd och snabbladdning.",
    features: ["MINI Connected", "LED-strålkastare", "Comfort Access", "Parkeringsassistent", "Navigationssystem", "Värme-/kylsäten"],
  },
];

// Helper: Extract unique values for filters
export const getUniqueMakes = () => Array.from(new Set(cars.map((c) => c.make))).sort();
export const getUniqueFuels = () => Array.from(new Set(cars.map((c) => c.fuel))).sort();
export const getUniqueTransmissions = () => Array.from(new Set(cars.map((c) => c.transmission))).sort();
export const getUniqueBodyTypes = () => Array.from(new Set(cars.map((c) => c.body))).sort();
export const getUniqueColors = () => Array.from(new Set(cars.map((c) => c.color))).sort();
