export type Car = {
  id: string;
  slug: string;
  make: string;
  model: string;
  year: number;
  mileage: number;
  fuel: string;
  transmission: string;
  drivetrain: string;
  body: string;
  bodyType: string;
  color: string;
  price: number;
  images: string[];
  featured: boolean;
  title: string;
  description: string;
  features: string[];
};

export const cars: Car[] = [
  {
    id: "1",
    slug: "volvo-v90-d4-awd",
    make: "Volvo",
    model: "V90 D4 AWD",
    title: "Volvo V90 D4 AWD",
    year: 2017,
    mileage: 12300,
    fuel: "Diesel",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "Kombi",
    bodyType: "Kombi",
    color: "Svart",
    price: 249900,
    images: ["https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&h=600&fit=crop"],
    featured: true,
    description: "Elegant och rymlig familjebil med kraftfull dieselmotor och fyrhjulsdrift. Perfekt för svenska vägar.",
    features: ["Läderklädsel", "Panoramatak", "Adaptiv farthållare", "Parkeringskamera", "LED-strålkastare", "Navigation"],
  },
  {
    id: "2",
    slug: "bmw-x5-xdrive30d",
    make: "BMW",
    model: "X5 xDrive30d",
    title: "BMW X5 xDrive30d",
    year: 2019,
    mileage: 8500,
    fuel: "Diesel",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "SUV",
    bodyType: "SUV",
    color: "Vit",
    price: 449900,
    images: ["https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop"],
    featured: true,
    description: "Premium SUV med exceptionell körglädje och avancerad teknik. Lyx och prestanda i perfekt balans.",
    features: ["Luftfjädring", "Head-up display", "Massage i säten", "Harman Kardon", "Elbaklucka", "Panoramatak"],
  },
  {
    id: "3",
    slug: "vw-golf-14-tsi",
    make: "Volkswagen",
    model: "Golf 1.4 TSI",
    title: "Volkswagen Golf 1.4 TSI",
    year: 2020,
    mileage: 4200,
    fuel: "Bensin",
    transmission: "Manuell",
    drivetrain: "FWD",
    body: "Halvkombi",
    bodyType: "Halvkombi",
    color: "Grå",
    price: 189900,
    images: ["https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800&h=600&fit=crop"],
    featured: false,
    description: "Pålitlig och bränslesnål stadsbil med modern utrustning. Perfekt för både stad och landsvägskörning.",
    features: ["Klimatanläggning", "Cruise control", "Apple CarPlay", "Parkeringssensorer", "Multifunktionsratt"],
  },
  {
    id: "4",
    slug: "audi-a4-avant-20-tdi",
    make: "Audi",
    model: "A4 Avant 2.0 TDI",
    title: "Audi A4 Avant 2.0 TDI",
    year: 2018,
    mileage: 9800,
    fuel: "Diesel",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "Kombi",
    bodyType: "Kombi",
    color: "Blå",
    price: 279900,
    images: ["https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop"],
    featured: false,
    description: "Stilren sportkombi med quattro fyrhjulsdrift. Elegant design möter praktisk funktionalitet.",
    features: ["MMI Navigation", "LED-strålkastare", "Elstol", "Parkeringskamera", "Adaptiv farthållare"],
  },
  {
    id: "5",
    slug: "tesla-model-3-long-range",
    make: "Tesla",
    model: "Model 3 Long Range",
    title: "Tesla Model 3 Long Range",
    year: 2021,
    mileage: 2100,
    fuel: "El",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "Sedan",
    bodyType: "Sedan",
    color: "Röd",
    price: 399900,
    images: ["https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&h=600&fit=crop"],
    featured: true,
    description: "Framtidens bil är här! Lång räckvidd, imponerande prestanda och självstyrande funktioner.",
    features: ["Autopilot", "15-tums pekskärm", "Premium ljudsystem", "Glastak", "Sportläge", "OTA-uppdateringar"],
  },
  {
    id: "6",
    slug: "mercedes-c-class-220d",
    make: "Mercedes-Benz",
    model: "C 220d",
    title: "Mercedes-Benz C 220d",
    year: 2019,
    mileage: 7200,
    fuel: "Diesel",
    transmission: "Automat",
    drivetrain: "RWD",
    body: "Sedan",
    bodyType: "Sedan",
    color: "Silver",
    price: 329900,
    images: ["https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&h=600&fit=crop"],
    featured: false,
    description: "Lyxsedan med klassisk elegans och moderna tekniklösningar. Komfort och prestanda i världsklass.",
    features: ["Burmester ljudsystem", "Ambient belysning", "MBUX", "Luftfjädring", "Keyless-Go", "Backkamera"],
  },
  {
    id: "7",
    slug: "volvo-xc60-t8",
    make: "Volvo",
    model: "XC60 T8 Twin Engine",
    title: "Volvo XC60 T8 Twin Engine",
    year: 2020,
    mileage: 5800,
    fuel: "Hybrid",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "SUV",
    bodyType: "SUV",
    color: "Vit",
    price: 459900,
    images: ["https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&h=600&fit=crop"],
    featured: true,
    description: "Kraftfull laddhybrid SUV med svensk design. Kombinerar prestanda med miljömedvetenhet.",
    features: ["Bowers & Wilkins", "360-kamera", "Pilot Assist", "Luftkonditionering", "Panoramatak", "Dragkrok"],
  },
  {
    id: "8",
    slug: "audi-q5-40-tdi",
    make: "Audi",
    model: "Q5 40 TDI",
    title: "Audi Q5 40 TDI",
    year: 2018,
    mileage: 11200,
    fuel: "Diesel",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "SUV",
    bodyType: "SUV",
    color: "Grå",
    price: 349900,
    images: ["https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&q=80"],
    featured: false,
    description: "Allsidig premium-SUV med quattro och Virtual Cockpit. Bekväm på långa resor.",
    features: ["Virtual Cockpit", "Bang & Olufsen", "Alcantara", "Elbaklucka", "Matrix LED", "Adaptive Cruise"],
  },
  {
    id: "9",
    slug: "bmw-3-series-320d",
    make: "BMW",
    model: "320d xDrive",
    title: "BMW 320d xDrive",
    year: 2017,
    mileage: 14500,
    fuel: "Diesel",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "Sedan",
    bodyType: "Sedan",
    color: "Svart",
    price: 239900,
    images: ["https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&h=600&fit=crop"],
    featured: false,
    description: "Sportsedan med perfekt balans mellan komfort och körglädje. BMW när det är som bäst.",
    features: ["M Sport paket", "Professional Navigation", "LED-strålkastare", "Adaptiv farthållare", "Sportläge"],
  },
  {
    id: "10",
    slug: "vw-passat-variant",
    make: "Volkswagen",
    model: "Passat Variant 2.0 TDI",
    title: "Volkswagen Passat Variant 2.0 TDI",
    year: 2019,
    mileage: 6700,
    fuel: "Diesel",
    transmission: "Automat",
    drivetrain: "FWD",
    body: "Kombi",
    bodyType: "Kombi",
    color: "Blå",
    price: 269900,
    images: ["https://images.unsplash.com/photo-1552519507-0b63f22e8ee4?w=800&h=600&fit=crop"],
    featured: false,
    description: "Rymlig och praktisk familjebil med moderna säkerhetssystem. Bekväm på alla resor.",
    features: ["Discover Pro", "Area View", "ACC", "LED Plus", "Elbaklucka", "Drag"],
  },
  {
    id: "11",
    slug: "toyota-rav4-hybrid",
    make: "Toyota",
    model: "RAV4 Hybrid AWD",
    title: "Toyota RAV4 Hybrid AWD",
    year: 2021,
    mileage: 3200,
    fuel: "Hybrid",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "SUV",
    bodyType: "SUV",
    color: "Silver",
    price: 369900,
    images: ["https://images.unsplash.com/photo-1581540222194-0def2dda95b8?w=800&h=600&fit=crop"],
    featured: true,
    description: "Pålitlig hybrid-SUV med låg bränsleförbrukning. Toyotas legendära kvalitet.",
    features: ["JBL Premium Sound", "Bi-LED", "Head-up display", "Adaptiv farthållare", "Backkamera", "Elstol"],
  },
  {
    id: "12",
    slug: "kia-sportage-phev",
    make: "Kia",
    model: "Sportage PHEV",
    title: "Kia Sportage PHEV",
    year: 2022,
    mileage: 1500,
    fuel: "Hybrid",
    transmission: "Automat",
    drivetrain: "AWD",
    body: "SUV",
    bodyType: "SUV",
    color: "Vit",
    price: 429900,
    images: ["https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=800&h=600&fit=crop"],
    featured: false,
    description: "Modern laddhybrid med imponerande räckvidd på el. Stilren design och rik utrustning.",
    features: ["12,3 tum skärm", "BOSE", "Panoramatak", "Adaptiv fjädring", "HUD", "Trådlös laddning"],
  },
];

// Helper: Extract unique values for filters
export const getUniqueMakes = () => Array.from(new Set(cars.map((c) => c.make))).sort();
export const getUniqueFuels = () => Array.from(new Set(cars.map((c) => c.fuel))).sort();
export const getUniqueTransmissions = () => Array.from(new Set(cars.map((c) => c.transmission))).sort();
export const getUniqueBodyTypes = () => Array.from(new Set(cars.map((c) => c.body))).sort();
export const getUniqueColors = () => Array.from(new Set(cars.map((c) => c.color))).sort();
